# fly.toml app configuration file generated for messagebd on 2023-07-24T10:12:14-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "messagebd"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
